# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
  - main

pool:
  name: rebecka_azure

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        node -v
        pnpm -v

        pnpm install
        "export const ID_SEM_INSTITUICAO=3" | Out-File -Encoding utf8 -FilePath ./src/utils/constantes.ts
        (Get-Content src/utils/http/index.ts) -replace 'https://hom-api\.ecossistemadeinovacaocg\.com\.br', "${env:API_URL}" | Set-Content src/utils/http/index.ts

        pnpm build
        Copy-Item -Path ./staticwebapp.config.json -Destination ./dist
        pnpx @azure/static-web-apps-cli deploy ./dist --env production
    env:
      SWA_CLI_DEPLOYMENT_TOKEN: $(DEPLOY_TOKEN)
      API_URL: $(API_URL)