# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
  - main

pool:
  name: rebecka_azure

variables:
  tag: "release"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "ecossistema registry"
      repository: "ecossistema-2024/deploy-container"
      command: "build"
      Dockerfile: "./Dockerfile"
      tags: "$(tag)"

  - task: Docker@2
    inputs:
      containerRegistry: "ecossistema registry"
      repository: "ecossistema-2024/deploy-container"
      command: "push"
      tags: "$(tag)"

  - script: |
      docker run --rm \
        -e API_URL=$(API_URL) \
        -e SWA_CLI_DEPLOYMENT_TOKEN=$(DEPLOY_TOKEN) \
        ecossistema-2024/deploy-container:$(tag)
    displayName: 'Run deploy container'
