# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'eldorado percepcao registry'
    repository: 'ecossistema'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- bash: |
    curl -X GET -H "X-TOKEN: $TOKEN" \
    https://startupsesi.brazilsouth.cloudapp.azure.com/push-hook?project=ecossistema
  displayName: "Alert server via webhook"
  env:
    TOKEN: $(PUSH-TOKEN)