# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  - main

resources:
  - repo: self

pool:
  name: rebecka_azure

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'    # Ajuste a versão conforme seu projeto
    displayName: 'Install Node.js'

  - bash: |
      pnpm i
      echo "export const ID_SEM_INSTITUICAO=3" > ./src/utils/constantes.ts
      sed -i 's|https://hom-api\.ecossistemadeinovacaocg\.com\.br|$(API_URL)|g' src/utils/http/index.ts
      pnpm build
      cp ./staticwebapp.config.json ./dist
      pnpx @azure/static-web-apps-cli deploy ./dist --env production
    env:
      SWA_CLI_DEPLOYMENT_TOKEN: $(DEPLOY_TOKEN)
    displayName: 'Install dependencies, build and deploy'
