# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: rebecka_azure

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'eldorado percepcao registry'
    repository: 'ecossistema'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'